Backport 55's snowflake driver to 54 (#327)
seemed to have non-deterministic issues with snowflake throwing the
following error:

> JDBC driver internal error: Max retry reached for the download of
chunk#0 (Total chunks: 2) retry: 7, error:
net.snowflake.client.jdbc.SnowflakeSQLLoggedException: JDBC driver
encountered communication error. Message: (certificate_unknown) No
trusted certificate found\nVerify that the hostnames and portnumbers in
SYSTEM$ALLOWLIST are added to your firewall's allowed list.\nTo
troubleshoot your connection further, you can refer to this
article:\nhttps://docs.snowflake.com/en/user-guide/client-connectivity-troubleshooting/overview.

```
2026-02-18 16:23:03,584 ERROR jdbc.SnowflakeChunkDownloader :: Downloader encountered error: Max retry reached for the download of chunk#0 (Total chunks: 2) retry: 7, error: net.snowflake.client.jdbc.SnowflakeSQLLoggedException: JDBC driver encountered communication error. Message: (certificate_unknown) No trusted certificate found
Verify that the hostnames and portnumbers in SYSTEM$ALLOWLIST are added to your firewall's allowed list.
To troubleshoot your connection further, you can refer to this article:
https://docs.snowflake.com/en/user-guide/client-connectivity-troubleshooting/overview.
        at net.snowflake.client.jdbc.RestRequest.execute(RestRequest.java:380)
        at net.snowflake.client.jdbc.RestRequest.execute(RestRequest.java:146)
        at net.snowflake.client.jdbc.DefaultResultStreamProvider.getResultChunk(DefaultResultStreamProvider.java:126)
        at net.snowflake.client.jdbc.DefaultResultStreamProvider.getInputStream(DefaultResultStreamProvider.java:45)
        at net.snowflake.client.jdbc.SnowflakeChunkDownloader$2.call(SnowflakeChunkDownloader.java:1021)
        at net.snowflake.client.jdbc.SnowflakeChunkDownloader$2.call(SnowflakeChunkDownloader.java:935)
        at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:328)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1090)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:614)
        at java.base/java.lang.Thread.run(Thread.java:1474)
Caused by: javax.net.ssl.SSLHandshakeException: (certificate_unknown) No trusted certificate found
        at java.base/sun.security.ssl.Alert.createSSLException(Alert.java:130)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:376)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:319)
        at java.base/sun.security.ssl.TransportContext.fatal(TransportContext.java:314)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:651)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.onCertificate(CertificateMessage.java:471)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.consume(CertificateMessage.java:367)
        at java.base/sun.security.ssl.SSLHandshake.consume(SSLHandshake.java:421)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:477)
        at java.base/sun.security.ssl.HandshakeContext.dispatch(HandshakeContext.java:448)
        at java.base/sun.security.ssl.TransportContext.dispatch(TransportContext.java:199)
        at java.base/sun.security.ssl.SSLTransport.decode(SSLTransport.java:172)
        at java.base/sun.security.ssl.SSLSocketImpl.decode(SSLSocketImpl.java:1506)
        at java.base/sun.security.ssl.SSLSocketImpl.readHandshakeRecord(SSLSocketImpl.java:1421)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:455)
        at java.base/sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:426)
        at net.snowflake.client.jdbc.internal.apache.http.conn.ssl.SSLConnectionSocketFactory.createLayeredSocket(SSLConnectionSocketFactory.java:436)
        at net.snowflake.client.jdbc.internal.apache.http.conn.ssl.SSLConnectionSocketFactory.connectSocket(SSLConnectionSocketFactory.java:384)
        at net.snowflake.client.jdbc.internal.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:142)
        at net.snowflake.client.jdbc.internal.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376)
        at net.snowflake.client.jdbc.internal.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393)
        at net.snowflake.client.jdbc.internal.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236)
        at net.snowflake.client.jdbc.internal.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186)
        at net.snowflake.client.jdbc.internal.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
        at net.snowflake.client.jdbc.internal.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110)
        at net.snowflake.client.jdbc.internal.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
        at net.snowflake.client.jdbc.internal.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83)
        at net.snowflake.client.jdbc.internal.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108)
        at net.snowflake.client.jdbc.RestRequest.execute(RestRequest.java:358)
        ... 9 more
Caused by: sun.security.validator.ValidatorException: No trusted certificate found
        at java.base/sun.security.validator.SimpleValidator.buildTrustedChain(SimpleValidator.java:414)
        at java.base/sun.security.validator.SimpleValidator.engineValidate(SimpleValidator.java:140)
        at java.base/sun.security.validator.Validator.validate(Validator.java:256)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:230)
        at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)
        at net.snowflake.client.core.SFTrustManager.checkServerTrusted(SFTrustManager.java:736)
        at java.base/sun.security.ssl.CertificateMessage$T12CertificateConsumer.checkServerCerts(CertificateMessage.java:635)
```

We think that snowflake is using an http connection to grab the results
and there are two copies of some classes on the classpath. Since the
snowflake jar is a fat jar it doesn't list its deps so we can make sure
we only have one copy. It's fat so it bundles it's own classes so it
might get it's own or might get others in the regular jar. I think it's
getting others non-deterministically and then throwing errors, catching
them, trying again, until it gives up and says

Downloader encountered error: Max retry reached for the download of
chunk#0 (Total chunks: 2) retry: 7, error:
net.snowflake.client.jdbc.SnowflakeSQLLoggedException: JDBC driver
encountered communication error. Message: (certificate_unknown) No
trusted certificate found