handle conflicts in jakarta.activation with hive fat jar
the hive fat jar includes some values it shouldn't. We want the classes
that result from:

```
com.github.oliyh/martian-clj-http 0.2.1
  . com.github.oliyh/martian 0.2.1
  ...
    X cheshire/cheshire 6.0.0 :use-top
    . com.cognitect/transit-clj 1.0.333
      . com.cognitect/transit-java 1.0.371
        X com.fasterxml.jackson.core/jackson-core 2.14.2 :older-version
        . org.msgpack/msgpack 0.6.12
        . javax.xml.bind/jaxb-api 2.4.0-b180830.0359 :newer-version
          . javax.activation/javax.activation-api 1.2.0 ;; <-----
```

and

```
com.sun.mail/jakarta.mail 1.6.8
  . com.sun.activation/jakarta.activation 1.2.1
```

The hive version has some package private classes which are causing
issues when sending emails:

```
java.lang.IllegalAccessError: failed to access class com.sun.activation.registries.LogSupport from class javax.activation.MailcapCommandMap (com.sun.activation.registries.LogSupport and javax.activation.MailcapCommandMap are in unnamed module of loader 'app')
        at javax.activation.MailcapCommandMap.<init>(MailcapCommandMap.java:179)
        at javax.activation.CommandMap.getDefaultCommandMap(CommandMap.java:85)
        at javax.activation.DataHandler.getCommandMap(DataHandler.java:167)
        at javax.activation.DataHandler.getDataContentHandler(DataHandler.java:629)
        at javax.activation.DataHandler.writeTo(DataHandler.java:329)
        at javax.mail.internet.MimeUtility.getEncoding(MimeUtility.java:316)
        at javax.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1551)
        at javax.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1148)
        at javax.mail.internet.MimeMultipart.updateHeaders(MimeMultipart.java:498)
        at javax.mail.internet.MimeBodyPart.updateHeaders(MimeBodyPart.java:1509)
        at javax.mail.internet.MimeMessage.updateHeaders(MimeMessage.java:2247)
        at postal.message.proxy$javax.mail.internet.MimeMessage$ff19274a.updateHeaders(Unknown Source)
        at javax.mail.internet.MimeMessage.saveChanges(MimeMessage.java:2207)
        at postal.message.proxy$javax.mail.internet.MimeMessage$ff19274a.saveChanges(Unknown Source)
        at postal.message$make_jmessage.invokeStatic(message.clj:214)
        at postal.message$make_jmessage.invoke(message.clj:178)
        at postal.smtp$smtp_send_STAR_$fn__123037.invoke(smtp.clj:34)
        at clojure.core$map$fn__5956.invoke(core.clj:2772)
        at clojure.lang.LazySeq.force(LazySeq.java:50)
        at clojure.lang.LazySeq.realize(LazySeq.java:89)
        at clojure.lang.LazySeq.seq(LazySeq.java:106)
        at clojure.lang.RT.seq(RT.java:555)
        at clojure.core$seq__5488.invokeStatic(core.clj:139)
        at clojure.core$seq__5488.invoke(core.clj:139)
        at postal.smtp$smtp_send_STAR_.invokeStatic(smtp.clj:35)
        at postal.smtp$smtp_send_STAR_.invoke(smtp.clj:29)
        at postal.smtp$smtp_send.invokeStatic(smtp.clj:58)
        at postal.smtp$smtp_send.doInvoke(smtp.clj:39)
        at clojure.lang.RestFn.invoke(RestFn.java:426)
        at postal.core$send_message.invokeStatic(core.clj:36)
```