Update c3p0 version from 0.10.1 to 0.11.2
From https://github.com/swaldman/c3p0/blob/0.11.x/CHANGELOG

c3p0-0.11.2
        -- Expose utilities `overwriteJavaBeanProperties` and `overwriteC3P0PrefixedProperties`
	   in the `DataSources` class, and refactor existing functions to use those.
c3p0-0.11.1
	-- in BasicResourcePool, forceKillAcquires() accidentally failed to surrender its lock,
	   leading to deadlocks following a full round of acquisition failures. Many thanks
	   to @pwielgolaski on github for tracking down the issue, to @driseley on github for
	   providing a reproduction of the issue, and to @michalgutkowski on github for providing
	   a pull request with the fix.
c3p0-0.11.0
	-- Additional testing.
c3p0-0.11.0-pre2
	-- Define new property cancelAutomaticallyClosedStatements, which, if true, ensures
	   that Statement.cancel() will be called prior to Statement.close() when c3p0 automatically
	   close()es statements because a client has neglected to, a Connection with open Statements
	   has exceeded its unreturnedConnectionTimeout, or the Statement cache is expiring a PreparedStatement.
	   Thanks to Andreas Dangel (in 2014!) for pointing out scenarios where this might be 
	   helpful, and offering a PR demonstrating the basic fix, and Luis Paolini for reminding me
	   that I flaked 11 years ago and this is still worth pursuing.
c3p0-0.11.0-pre1
	-- Rewrite BasicResourcePool and GooGooStatementCache in terms of
	   ReentrantLock and Condition.{await/signalAll} rather than native
	   monitors and wait()/notifyAll(), because wait() pins loom
	   virtual threads. Many thanks to alex-kormukhin for calling
	   attention to this issue and proposing the fix!
	-- Double check after termination of BasicResourcePool.awaitAvailable(...)
	   that following notification/termination a resource (Connection) remains
	   available. Many thanks to C3Stones and xtb359 on github for calling
	   attention to this issue.
	-- Prevent fragility under non-bootstrap / non-system CLASSLOADERs under
	   Java 8, where references to java.sql.ShardingKey not available under Java 8
	   provoke NoClassDefFoundError. Bifurcate Connection proxies, generate
	   version without sharding key methods under JVMs where ShardingKey is unavailable,
	   full JDBC 4.3 Connection API proxies where ShardingKey is present.
	   Thanks to Force Rs on github for finding the issue and suggesting the
	   solution!
c3p0-0.10.2
	-- Prevent freeze due to re-waiting if a non-Exception Throwable occurs
	   while acquiring a PreparedStatement to cache. Thanks Totyo Totev!