Slightly rework error handling for site URL
Instead of using assert, which throws an exception with confusing detail
for the users, use a more user-friendly error.

Old error:

    Error: Assert failed: Invalid site URL: "https://localhost:3000!"
(u/url? s)

New error:

    Error: Invalid site URL: "http://localhost:3000!"

Resolves #4506