handle measures/metrics that lack a definition
tests caught these but real stuff could totally have this

FAIL in metabase-enterprise.remote-sync.impl-test/export!-excludes-archived-measures-test (impl_test.clj:1025)
export! excludes archived measures from export (via skip-archived flag)
(with-model-cleanup "RemoteSyncObject" "Measure")

Setting :remote-sync-type = :read-write

with temporary :model/Database

with temporary :model/Collection

with temporary :model/Table

with temporary :model/Measure

with temporary :model/Measure

expected: :success
  actual: :error

FAIL in metabase-enterprise.remote-sync.impl-test/export!-excludes-archived-measures-test (impl_test.clj:1028)
export! excludes archived measures from export (via skip-archived flag)
(with-model-cleanup "RemoteSyncObject" "Measure")

Setting :remote-sync-type = :read-write

with temporary :model/Database

with temporary :model/Collection

with temporary :model/Table

with temporary :model/Measure

with temporary :model/Measure

Active measure should be exported. Keys: ("collections/M-Q4pcV0qkiyJ0kiSWECl_some_collection/M-Q4pcV0qkiyJ0kiSWECl_some_collection.yaml" "collections/M-Q4pcV0qkiyJ0kiSWECl_some_collection/cards/f1C68pznmrpN1F5xFDj6d_some_question.yaml" "collections/M-Q4pcV0qkiyJ0kiSWECl_some_collection/dashboards/Q_jD-f-9clKLFZ2TfUG2h_shared_dashboard.yaml")
expected: (some
           (fn* [p1__314668#] (str/includes? p1__314668# "active_measure"))
           file-keys)
  actual: (not
           (some
            #<Fn@2c1faff4 metabase_enterprise.remote_sync.impl_test/fn__314670[fn/fn/fn/fn/fn/fn/fn/fn/fn]>
            ("collections/M-Q4pcV0qkiyJ0kiSWECl_some_collection/M-Q4pcV0qkiyJ0kiSWECl_some_collection.yaml"
             "collections/M-Q4pcV0qkiyJ0kiSWECl_some_collection/cards/f1C68pznmrpN1F5xFDj6d_some_question.yaml"
             "collections/M-Q4pcV0qkiyJ0kiSWECl_some_collection/dashboards/Q_jD-f-9clKLFZ2TfUG2h_shared_dashboard.yaml")))

ERROR in metabase-enterprise.serialization.v2.extract-test/collection-export-includes-fields-and-segments-test (serialization.clj:536)
Uncaught exception, not in assertion.

clojure.lang.ExceptionInfo: Error extracting Segment 1
                    cause: "Error extracting Segment 1"
                entity_id: "FTAODs9FCLwPAsC-_7Nb3"
                       id: 1
                    model: "Segment"
                    table: :segment
    toucan2/context-trace: [["execute SQL with class org.h2.jdbc.JdbcConnection"
                             #:toucan2.jdbc.query{:sql-args ["SELECT * FROM \"SEGMENT\" WHERE \"ID\" IN (?)" 1]}]
                            ["resolve connection" #:toucan2.connection{:connectable org.h2.jdbc.JdbcConnection}]
                            ["resolve connection" #:toucan2.connection{:connectable nil}]
                            #:toucan2.pipeline{:rf #function[clojure.core/map/fn--5952/fn--5953]}
                            ["with compiled query" #:toucan2.pipeline{:compiled-query ["SELECT * FROM \"SEGMENT\" WHERE \"ID\" IN (?)" 1]}]
                            ["with built query" #:toucan2.pipeline{:built-query {:select [:*], :from [[:segment]], :where [:in :id [1]]}}]
                            ["with resolved query" #:toucan2.pipeline{:resolved-query {:where [:in :id [1]]}}]
                            ["with parsed args"
                             #:toucan2.pipeline{:query-type :toucan.query-type/select.instances,
                                                :parsed-args {:queryable {:where [:in :id [1]]}}}]
                            ["with model" #:toucan2.pipeline{:model :model/Segment}]
                            ["with unparsed args"
                             #:toucan2.pipeline{:query-type :toucan.query-type/select.instances,
                                                :unparsed-args (:model/Segment {:where [:in :id [1]]})}]
                            ...]
clojure.lang.ExceptionInfo: Error extracting Segment 1
        error: {:schema [:ref :metabase.lib.schema/query],
                :value {},
                :errors
                ({:path [0 0 0 :lib/type],
                  :in [:lib/type],
                  :schema