more closing up after the request
I think we are still leaking threads when we get errors with responses
like

```
:cause Deflater has been closed, :_status 500}
java.lang.NullPointerException: Deflater has been closed
	at java.base/java.util.zip.Deflater.ensureOpen(Deflater.java:902)
	at java.base/java.util.zip.Deflater.deflate(Deflater.java:564)
	at java.base/java.util.zip.Deflater.deflate(Deflater.java:464)
	at java.base/java.util.zip.GZIPOutputStream.finish(GZIPOutputStream.java:163)
	at java.base/java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:244)
	at metabase.async.streaming_response$delay_output_stream$fn__52042.invoke(streaming_response.clj:121)
	at metabase.async.streaming_response.proxy$java.io.OutputStream$ff19274a.close(Unknown Source)
	at java.base/sun.nio.cs.StreamEncoder.implClose(StreamEncoder.java:439)
	at java.base/sun.nio.cs.StreamEncoder.lockedClose(StreamEncoder.java:237)
	at java.base/sun.nio.cs.StreamEncoder.close(StreamEncoder.java:222)
	at java.base/java.io.OutputStreamWriter.close(OutputStreamWriter.java:266)
	at java.base/java.io.BufferedWriter.implClose(BufferedWriter.java:398)
	at java.base/java.io.BufferedWriter.close(BufferedWriter.java:380)
	at metabase.async.streaming_response$write_error_BANG_.invokeStatic(streaming_response.clj:60)
	at metabase.async.streaming_response$write_error_BANG_.invoke(streaming_response.clj:45)
	at metabase.async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:78)
	at metabase.async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:66)
	at metabase.async.streaming_response$do_f_async$task__52027.invoke(streaming_response.clj:88)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
2024-07-03 14:44:53,189 ERROR async.streaming-response :: bound-fn caught unexpected Exception
java.lang.NullPointerException: Deflater has been closed
	at java.base/java.util.zip.Deflater.ensureOpen(Deflater.java:902)
	at java.base/java.util.zip.Deflater.deflate(Deflater.java:564)
	at java.base/java.util.zip.Deflater.deflate(Deflater.java:464)
	at java.base/java.util.zip.GZIPOutputStream.finish(GZIPOutputStream.java:163)
	at java.base/java.util.zip.DeflaterOutputStream.close(DeflaterOutputStream.java:244)
	at metabase.async.streaming_response$delay_output_stream$fn__52042.invoke(streaming_response.clj:121)
	at metabase.async.streaming_response.proxy$java.io.OutputStream$ff19274a.close(Unknown Source)
	at metabase.async.streaming_response$write_error_BANG_.invokeStatic(streaming_response.clj:57)
	at metabase.async.streaming_response$write_error_BANG_.invoke(streaming_response.clj:45)
	at metabase.async.streaming_response$do_f_STAR_.invokeStatic(streaming_response.clj:78)
	at metabase.async.streaming_response$do_f_STAR_.invoke(streaming_response.clj:66)
	at metabase.async.streaming_response$do_f_async$task__52027.invoke(streaming_response.clj:88)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:572)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
	at java.base/java.lang.Thread.run(Thread.java:1583)
```